final List<String> myGoogleFonts = [
  // "Abril Fatface",
  // "Aclonica",
  // "Alegreya Sans",
  // "Architects Daughter",
  // "Archivo",
  // "Archivo Narrow",
  // "Bebas Neue",
  // "Bitter",
  // "Bree Serif",
  // "Bungee",
  // "Cabin",
  // "Cairo",
  // "Coda",
  // "Comfortaa",
  // "Comic Neue",
  // "Cousine",
  // "Croissant One",
  // "Faster One",
  // "Forum",
  // "Great Vibes",
  // "Heebo",
  // "Inconsolata",
  "Inter",
  // "Josefin Slab",
  "Lato",
  // "Libre Baskerville",
  // "Lobster",
  "Lora",
  "Merriweather",
  "Montserrat",
  // "Mukta",
  "Nunito",
  // "Offside",
  "Open Sans",
  "Oswald",
  // "Overlock",
  // "Pacifico",
  // "Playfair Display",
  "Poppins",
  "Raleway",
  "Roboto",
  "Roboto Mono",
  "Source Sans Pro",
  // "Space Mono",
  // "Spicy Rice",
  // "Squada One",
  // "Sue Ellen Francisco",
  // "Trade Winds",
  "Ubuntu",
  // "Varela",
  // "Vollkorn",
  // "Work Sans",
  // "Zilla Slab",
];
